# Generated by Django 6.0.1 on 2026-01-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceCategory',
            new_name='ServiceType',
        ),
    ]
