# Generated by Django 6.0.1 on 2026-02-04 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_icon_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='services.service'),
        ),
    ]
