# Generated by Django 6.0.1 on 2026-01-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
